import type { Product } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "True Hoodie",
    price: 9750,
    category: "hoodies",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/black-streetwear-hoodie-with-graphics.jpg",
    images: [
      "/black-streetwear-hoodie-with-graphics.jpg",
      "/black-streetwear-hoodie-back-view.jpg",
      "/black-streetwear-hoodie-detail.jpg",
    ],
    description: "Premium streetwear hoodie crafted from soft cotton blend for ultimate comfort.",
  },
  {
    id: "2",
    name: "Pleasant Cap",
    price: 7200,
    category: "accessories",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/black-streetwear-cap-with-embroidered-logo.jpg",
    images: [
      "/black-streetwear-cap-with-embroidered-logo.jpg",
      "/black-streetwear-cap-side-view.jpg",
      "/black-streetwear-cap-worn.jpg",
    ],
    description: "Made from premium materials, this cap is designed to keep you looking fresh.",
  },
  {
    id: "3",
    name: "Urban Joggers",
    price: 8700,
    category: "joggers",
    gender: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/beige-streetwear-jogger-pants.jpg",
    images: [
      "/beige-streetwear-jogger-pants.jpg",
      "/beige-streetwear-jogger-detail.jpg",
      "/beige-streetwear-jogger-worn.jpg",
    ],
    description: "Comfortable joggers with tapered fit for the modern streetwear look.",
  },
  {
    id: "4",
    name: "Graphic Tee",
    price: 3800,
    category: "t-shirts",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/black-graphic-tee-streetwear.png",
    images: ["/black-graphic-tee-streetwear.png", "/black-graphic-tee-back.jpg", "/black-graphic-tee-detail.jpg"],
    description: "Bold graphic tee that makes a statement.",
  },
  {
    id: "5",
    name: "Street Shorts",
    price: 5250,
    category: "shorts",
    gender: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/black-streetwear-cargo-shorts.jpg",
    images: [
      "/black-streetwear-cargo-shorts.jpg",
      "/black-streetwear-cargo-shorts-detail.jpg",
      "/black-streetwear-cargo-shorts-worn.jpg",
    ],
    description: "Relaxed fit cargo shorts perfect for summer vibes.",
  },
  {
    id: "6",
    name: "Oversized Hoodie",
    price: 10350,
    category: "hoodies",
    gender: "women",
    sizes: ["S", "M", "L", "XL"],
    image: "/cream-oversized-hoodie-women-streetwear.jpg",
    images: [
      "/cream-oversized-hoodie-women-streetwear.jpg",
      "/cream-oversized-hoodie-back.jpg",
      "/cream-oversized-hoodie-detail.jpg",
    ],
    description: "Cozy oversized hoodie with dropped shoulders.",
  },
  {
    id: "7",
    name: "Vintage Jacket",
    price: 12600,
    category: "hoodies",
    gender: "women",
    sizes: ["S", "M", "L", "XL"],
    image: "/vintage-brown-leather-jacket-women.jpg",
    images: [
      "/vintage-brown-leather-jacket-women.jpg",
      "/vintage-brown-leather-jacket-back.jpg",
      "/vintage-brown-leather-jacket-detail.jpg",
    ],
    description: "Vintage-inspired jacket with modern streetwear edge.",
  },
  {
    id: "8",
    name: "Cropped Tee",
    price: 2950,
    category: "t-shirts",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    image: "/white-cropped-t-shirt-women-streetwear.jpg",
    images: [
      "/white-cropped-t-shirt-women-streetwear.jpg",
      "/white-cropped-t-shirt-back.jpg",
      "/white-cropped-t-shirt-worn.jpg",
    ],
    description: "Trendy cropped tee for a modern look.",
  },
]

export const categoryData = [
  {
    id: "hoodies",
    name: "Hoodies",
    image: "/streetwear-hoodie-collection-dark-aesthetic.jpg",
    count: 3,
  },
  {
    id: "joggers",
    name: "Joggers",
    image: "/streetwear-joggers-pants-urban-style.jpg",
    count: 1,
  },
  {
    id: "shorts",
    name: "Shorts",
    image: "/streetwear-cargo-shorts-summer-style.jpg",
    count: 1,
  },
  {
    id: "t-shirts",
    name: "T-Shirts",
    image: "/graphic-tees-streetwear-collection.jpg",
    count: 2,
  },
  {
    id: "accessories",
    name: "Accessories",
    image: "/streetwear-caps-accessories-urban-fashion.jpg",
    count: 1,
  },
]
